name: Accessory
version: '1.3.6'
main: com.blanoir.accessory.Accessory
api-version: '1.21'
depend: [AuraSkills]
softdepend: [PlaceholderAPI, KeyBind, MythicMobs]
commands:
  shieldcur:
    description: Modify current absorb shield (does not change max)
    usage: /shieldcur <give|givep> <me|player|all> <value>
    permission: accessory.shieldcur

  inv:
    description: Open the own accessory bag
    usage: /acc
    aliases: [ acc ]
  accessory:
    description: Accessory management command
    usage: /accessory reload | /accessory clear <player>
    aliases: [ acre ]
permissions:
  accessory.reload:
    description: Allow Reloaded
    default: op
  accessory.clear:
    description: Allow clearing player accessories
    default: op
