name: Accessory
version: '1.2.5'
main: com.blanoir.accessory.Accessory
api-version: '1.21'
depend: [AuraSkills]
softdepend: [PlaceholderAPI]
commands:
  inv:
    description: Open the own accessory bag
    usage: /acc
    aliases: [ acc ]
  accessory:
    description: Accessory Reload command
    usage: /accessory reload
    aliases: [ acre ]
permissions:
  accessory.reload:
    description: Allow Reloaded
    default: op