name: Accessory
version: '2.0.0'
main: com.blanoir.accessory.Accessory
api-version: '1.21'
depend: [AuraSkills]
softdepend: [PlaceholderAPI, KeyBind, MythicMobs]
commands:
  shield:
    description: 调整当前物理护盾（不改上限）
    usage: /shield <give|givep> <me|player|all> <value>
    permission: accessory.shield
  magicshield:
    description: 调整当前魔法护盾（不改上限）
    usage: /magicshield <give|givep> <me|player|all> <value>
    permission: accessory.magicshield

  accessory:
    description: 打开你的饰品背包，或执行管理命令
    usage: /accessory [open|reload|clear <player>]
    aliases: [ acc, acre ]
permissions:
  accessory.reload:
    description: Allow Reloaded
    default: op
  accessory.clear:
    description: Allow clearing player accessories
    default: op
  accessory.shield:
    description: Allow adjusting physical shield
    default: op
  accessory.magicshield:
    description: Allow adjusting magic shield
    default: op
